const products = [
  {
    id: 1,
    img: "/media/jerseys/ajax1997.jpg",
    description: "Camiseta Ajax titular 1997",
    price: 70000,
    clubOrSeleccion: "club",
    equipo: "ajax",
    year: 1997,
    continent: "europa",
    cantCart: 0,
    stock: 2,
  },
  {
    id: 2,
    img: "/media/jerseys/alemania2014.jpg",
    description: "Camiseta Alemania 2014",
    price: 55000,
    clubOrSeleccion: "seleccion",
    equipo: "alemania",
    year: 2014,
    continent: "europa",
    cantCart: 0,
    stock: 1,
  },
  {
    id: 3,
    img: "/media/jerseys/argentina1978.jpg",
    description: "Camiseta Argentina 1978",
    price: 80000,
    clubOrSeleccion: "seleccion",
    equipo: "argentina",
    year: 1978,
    continent: "sudamerica",
    cantCart: 0,
    stock: 4,
  },
  {
    id: 4,
    img: "/media/jerseys/argentina1994.png",
    description: "Camiseta Argentina 1994",
    price: 75000,
    clubOrSeleccion: "seleccion",
    equipo: "argentina",
    year: 1994,
    continent: "sudamerica",
    cantCart: 0,
    stock: 3,
  },
  {
    id: 5,
    img: "/media/jerseys/argentinosjuniors1996.jpg",
    description: "Camiseta Argentinos Juniors 1996",
    price: 72000,
    clubOrSeleccion: "club",
    equipo: "argentinos juniors",
    year: 1996,
    continent: "sudamerica",
    cantCart: 0,
    stock: 1,
  },
  {
    id: 6,
    img: "/media/jerseys/arsenal2002.png",
    description: "Camiseta Arsenal 2002",
    price: 58000,
    clubOrSeleccion: "club",
    equipo: "arsenal",
    year: 2002,
    continent: "europa",
    cantCart: 0,
    stock: 1,
  },
  {
    id: 7,
    img: "/media/jerseys/barcelona1995.jpg",
    description: "Camiseta Suplente Barcelona 1995",
    price: 85000,
    clubOrSeleccion: "club",
    equipo: "barcelona",
    year: 1995,
    continent: "europa",
    cantCart: 0,
    stock: 2,
  },
  {
    id: 8,
    img: "/media/jerseys/barcelona1996.jpeg",
    description: "Camiseta Barcelona 1996",
    price: 78000,
    clubOrSeleccion: "club",
    equipo: "barcelona",
    year: 1996,
    continent: "europa",
    cantCart: 0,
    stock: 4,
  },
  {
    id: 9,
    img: "/media/jerseys/barcelona1999.jpg",
    description: "Camiseta Barcelona 1999",
    price: 70000,
    clubOrSeleccion: "club",
    equipo: "barcelona",
    year: 1999,
    continent: "europa",
    cantCart: 0,
    stock: 3,
  },
  {
    id: 10,
    img: "/media/jerseys/bayernmunich2021.jpg",
    description: "Camiseta Bayern Munich 2021",
    price: 45000,
    clubOrSeleccion: "club",
    equipo: "bayern munich",
    year: 2021,
    continent: "europa",
    cantCart: 0,
    stock: 4,
  },
  {
    id: 11,
    img: "/media/jerseys/boca1995.jpg",
    description: "Camiseta Boca 1995",
    price: 60000,
    clubOrSeleccion: "club",
    equipo: "boca",
    year: 1995,
    continent: "europa",
    cantCart: 0,
    stock: 2,
  },
  {
    id: 12,
    img: "/media/jerseys/boca2001.webp",
    description: "Camiseta Boca 2001",
    price: 48000,
    clubOrSeleccion: "club",
    equipo: "boca",
    year: 2001,
    continent: "sudamerica",
    cantCart: 0,
    stock: 4,
  },
  {
    id: 13,
    img: "/media/jerseys/borussia2024.jpg",
    description: "Camiseta Borussia Dortmund 2024",
    price: 39000,
    clubOrSeleccion: "club",
    equipo: "borussia dortmund",
    year: 2024,
    continent: "europa",
    cantCart: 0,
    stock: 3,
  },
  {
    id: 14,
    img: "/media/jerseys/brasil2002.jpeg",
    description: "Camiseta Brasil 2002",
    price: 68000,
    clubOrSeleccion: "seleccion",
    equipo: "brasil",
    year: 2002,
    continent: "sudamerica",
    cantCart: 0,
    stock: 5,
  },
  {
    id: 15,
    img: "/media/jerseys/brasil2018.jpg",
    description: "Camiseta Suplente Brasil 2018",
    price: 50000,
    clubOrSeleccion: "seleccion",
    equipo: "brasil",
    year: 2018,
    continent: "sudamerica",
    cantCart: 0,
    stock: 3,
  },
  {
    id: 16,
    img: "/media/jerseys/brasil2022.webp",
    description: "Camiseta Brasil 2022",
    price: 48000,
    clubOrSeleccion: "seleccion",
    equipo: "brasil",
    year: 2022,
    continent: "sudamerica",
    cantCart: 0,
    stock: 2,
  },
  {
    id: 17,
    img: "/media/jerseys/croacia1998.webp",
    description: "Camiseta Suplente Croacia 1998",
    price: 66000,
    clubOrSeleccion: "seleccion",
    equipo: "croacia",
    year: 1998,
    continent: "europa",
    cantCart: 0,
    stock: 1,
  },
  {
    id: 18,
    img: "/media/jerseys/cruzeiro2023.jpg",
    description: "Camiseta Cruzeiro 2023",
    price: 40000,
    clubOrSeleccion: "club",
    equipo: "cruzeiro",
    year: 2023,
    continent: "sudamerica",
    cantCart: 0,
    stock: 4,
  },
  {
    id: 19,
    img: "/media/jerseys/docksud2023.webp",
    description: "Camiseta Dock Sud 2023",
    price: 30000,
    clubOrSeleccion: "club",
    equipo: "dock sud",
    year: 2023,
    continent: "sudamerica",
    cantCart: 0,
    stock: 3,
  },
  {
    id: 20,
    img: "/media/jerseys/españa2010.jpg",
    description: "Camiseta España 2010",
    price: 61000,
    clubOrSeleccion: "seleccion",
    equipo: "españa",
    year: 2010,
    continent: "europa",
    cantCart: 0,
    stock: 2,
  },
  {
    id: 21,
    img: "/media/jerseys/fluminense2021.jpg",
    description: "Camiseta Fluminense 2021",
    price: 32000,
    clubOrSeleccion: "club",
    equipo: "fluminense",
    year: 2021,
    continent: "sudamerica",
    cantCart: 0,
    stock: 4,
  },
  {
    id: 22,
    img: "/media/jerseys/gremio2021.jpeg",
    description: "Camiseta Gremio 2021",
    price: 44000,
    clubOrSeleccion: "club",
    equipo: "gremio",
    year: 2021,
    continent: "sudamerica",
    cantCart: 0,
    stock: 1,
  },
  {
    id: 23,
    img: "/media/jerseys/holanda1988.jpeg",
    description: "Camiseta Holanda 1988",
    price: 80000,
    clubOrSeleccion: "seleccion",
    equipo: "holanda",
    year: 1988,
    continent: "europa",
    cantCart: 0,
    stock: 3,
  },
  {
    id: 24,
    img: "/media/jerseys/independiente2019.jpg",
    description: "Camiseta Independiente 2019",
    price: 52000,
    clubOrSeleccion: "club",
    equipo: "independiente",
    year: 2019,
    continent: "sudamerica",
    cantCart: 0,
    stock: 2,
  },
  {
    id: 25,
    img: "/media/jerseys/independiente1987.jpg",
    description: "Camiseta Independiente 1987",
    price: 79000,
    clubOrSeleccion: "club",
    equipo: "independiente",
    year: 1987,
    continent: "sudamerica",
    cantCart: 0,
    stock: 4,
  },
  {
    id: 26,
    img: "/media/jerseys/independiente1997.jpeg",
    description: "Camiseta Independiente 1997",
    price: 72000,
    clubOrSeleccion: "club",
    equipo: "independiente",
    year: 1997,
    continent: "sudamerica",
    cantCart: 0,
    stock: 1,
  },
  {
    id: 27,
    img: "/media/jerseys/independiente2004.webp",
    description: "Camiseta Independiente 2004",
    price: 61000,
    clubOrSeleccion: "club",
    equipo: "independiente",
    year: 2004,
    continent: "sudamerica",
    cantCart: 0,
    stock: 3,
  },
  {
    id: 28,
    img: "/media/jerseys/independiente2016.jpg",
    description: "Camiseta Independiente 2016",
    price: 59000,
    clubOrSeleccion: "club",
    equipo: "independiente",
    year: 2016,
    continent: "sudamerica",
    cantCart: 0,
    stock: 2,
  },
  {
    id: 29,
    img: "/media/jerseys/independiente2022.jpg",
    description: "Camiseta Independiente 2022",
    price: 52000,
    clubOrSeleccion: "club",
    equipo: "independiente",
    year: 2022,
    continent: "sudamerica",
    cantCart: 0,
    stock: 4,
  },
  {
    id: 30,
    img: "/media/jerseys/independiente2023.jpg",
    description: "Camiseta Independiente 2023",
    price: 49000,
    clubOrSeleccion: "club",
    equipo: "independiente",
    year: 2023,
    continent: "sudamerica",
    cantCart: 0,
    stock: 1,
  },
  {
    id: 31,
    img: "/media/jerseys/independiente2023s.jpg",
    description: "Camiseta Independiente",
    price: 49000,
    clubOrSeleccion: "club",
    equipo: "independiente",
    year: 2023,
    continent: "sudamerica",
    cantCart: 0,
    stock: 3,
  },
  {
    id: 32,
    img: "/media/jerseys/juventus1952.jpg",
    description: "Camiseta Juventus 1952",
    price: 90000,
    clubOrSeleccion: "club",
    equipo: "juventus",
    year: 1952,
    continent: "europa",
    cantCart: 0,
    stock: 2,
  },
  {
    id: 33,
    img: "/media/jerseys/manchesterunited2009.webp",
    description: "Camiseta Manchester United 2009",
    price: 64000,
    clubOrSeleccion: "club",
    equipo: "manchester united",
    year: 2009,
    continent: "europa",
    cantCart: 0,
    stock: 4,
  },
  {
    id: 34,
    img: "/media/jerseys/milan2006.webp",
    description: "Camiseta Milan 2006",
    price: 68000,
    clubOrSeleccion: "club",
    equipo: "milan",
    year: 2006,
    continent: "europa",
    cantCart: 0,
    stock: 1,
  },
  {
    id: 35,
    img: "/media/jerseys/milan2009.jpg",
    description: "Camiseta Milan 2009",
    price: 62000,
    clubOrSeleccion: "club",
    equipo: "milan",
    year: 2009,
    continent: "europa",
    cantCart: 0,
    stock: 3,
  },
  {
    id: 36,
    img: "/media/jerseys/napoli1987.jpg",
    description: "Camiseta Napoli 1987",
    price: 77000,
    clubOrSeleccion: "club",
    equipo: "napoli",
    year: 1987,
    continent: "europa",
    cantCart: 0,
    stock: 2,
  },
  {
    id: 37,
    img: "/media/jerseys/palmeiras2023.png",
    description: "Camiseta Suplente Palmeiras 2023",
    price: 43000,
    clubOrSeleccion: "club",
    equipo: "palmeiras",
    year: 2023,
    continent: "sudamerica",
    cantCart: 0,
    stock: 1,
  },
  {
    id: 38,
    img: "/media/jerseys/psg2023.webp",
    description: "Camiseta PSG 2023",
    price: 50000,
    clubOrSeleccion: "club",
    equipo: "paris saint german",
    year: 2023,
    continent: "europa",
    cantCart: 0,
    stock: 3,
  },
  {
    id: 39,
    img: "/media/jerseys/river1999.png",
    description: "Camiseta River 1999",
    price: 52000,
    clubOrSeleccion: "club",
    equipo: "river",
    year: 1999,
    continent: "sudamerica",
    cantCart: 0,
    stock: 2,
  },
  {
    id: 40,
    img: "/media/jerseys/santos2021.jpeg",
    description: "Camiseta Santos 2021",
    price: 42000,
    clubOrSeleccion: "club",
    equipo: "santos",
    year: 2021,
    continent: "sudamerica",
    cantCart: 0,
    stock: 1,
  },
  {
    id: 41,
    img: "/media/jerseys/velez2023.webp",
    description: "Camiseta Velez 2023",
    price: 43000,
    clubOrSeleccion: "club",
    equipo: "velez",
    year: 2023,
    continent: "sudamerica",
    cantCart: 0,
    stock: 3,
  },
];
if (!localStorage.getItem("products")) {
  localStorage.setItem("products", stringify(products));
}
